name: crm_flutter_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dio: ^5.2.0+1
  uuid: ^3.0.7
  flutter_staggered_grid_view: ^0.6.2
  http_mock_adapter: ^0.4.4
  talker_dio_logger: ^2.0.0
  shared_preferences: ^2.1.2
  test: ^1.22.0
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/fonts/
    - assets/json/

get_cli:
  sub_folder: false

flutter_gen: 
  output: lib/gen/
  integrations: 
    flutter_svg: true
  line_length: 80
